### ISSUE TITLE
Unable to send Database notification

### ISSUE THREAD

**Issue by ErnestStaug** [eyewitness/eye#21]
Hello,

I'm getting this error quite few times a day :)

```
[2018-03-14 00:34:02] production.ERROR: Eyewitness: Unable to send Database notification {"exception":"Trying to get property of non-object","data":null} 
[2018-03-14 00:34:02] production.ERROR: Trying to get property of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property of non-object at /var/www/webroot/app/vendor/eyewitness/eye/app/Notifications/Messages/Scheduler/Working.php:39)
[stacktrace]
#0 /var/www/webroot/app/vendor/eyewitness/eye/app/Notifications/Messages/Scheduler/Working.php(39): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to get p...', '/var/www/webroo...', 39, Array)
#1 /var/www/webroot/app/vendor/eyewitness/eye/app/Notifications/Drivers/Slack.php(35): Eyewitness\\Eye\\Notifications\\Messages\\Scheduler\\Working->meta()
#2 /var/www/webroot/app/vendor/eyewitness/eye/app/Notifications/Notifier.php(47): Eyewitness\\Eye\\Notifications\\Drivers\\Slack->fire(Object(Eyewitness\\Eye\\Repo\\Notifications\\Recipient), Object(Eyewitness\\Eye\\Notifications\\Messages\\Scheduler\\Working))
#3 /var/www/webroot/app/vendor/eyewitness/eye/app/Notifications/Notifier.php(28): Eyewitness\\Eye\\Notifications\\Notifier->sendTo(Object(Eyewitness\\Eye\\Repo\\Notifications\\Recipient), Object(Eyewitness\\Eye\\Notifications\\Messages\\Scheduler\\Working))
#4 /var/www/webroot/app/vendor/eyewitness/eye/app/Scheduling/BaseEvent.php(251): Eyewitness\\Eye\\Notifications\\Notifier->alert(Object(Eyewitness\\Eye\\Notifications\\Messages\\Scheduler\\Working))
#5 /var/www/webroot/app/vendor/eyewitness/eye/app/Scheduling/BaseEvent.php(283): Eyewitness\\Eye\\Scheduling\\Event->handleNotifications()
#6 /var/www/webroot/app/vendor/eyewitness/eye/app/Scheduling/Event.php(55): Eyewitness\\Eye\\Scheduling\\Event->runCommandInForeground(Object(Illuminate\\Foundation\\Application))
#7 /var/www/webroot/app/vendor/eyewitness/eye/app/Scheduling/CustomEvents.php(62): Eyewitness\\Eye\\Scheduling\\Event->run(Object(Illuminate\\Foundation\\Application))
#8 /var/www/webroot/app/vendor/eyewitness/eye/app/Commands/BackgroundRunCommand.php(66): Eyewitness\\Eye\\Commands\\BackgroundRunCommand->runEvent(Object(Illuminate\\Console\\Scheduling\\Event), true)
#9 [internal function]: Eyewitness\\Eye\\Commands\\BackgroundRunCommand->handle()
#10 /var/www/webroot/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#11 /var/www/webroot/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /var/www/webroot/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#13 /var/www/webroot/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#14 /var/www/webroot/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#15 /var/www/webroot/app/vendor/symfony/console/Command/Command.php(252): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#16 /var/www/webroot/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#17 /var/www/webroot/app/vendor/symfony/console/Application.php(946): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /var/www/webroot/app/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Eyewitness\\Eye\\Commands\\BackgroundRunCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /var/www/webroot/app/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /var/www/webroot/app/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /var/www/webroot/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /var/www/webroot/app/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 {main}
"} 
```

Any ideas how to solve it?

**Comment by indigoram89** [comment]
a have this error too

**Comment by vehcklox** [comment]
I am getting this issue as well. It is happening for email notifications.

```[2018-03-15 17:00:16] production.ERROR: Eyewitness: Unable to send Database notification {"exception":"Trying to get property of non-object","data":null}
[2018-03-15 17:00:16] production.ERROR: Eyewitness: Unable to send Email noitification {"exception":"Trying to get property of non-object (View: /path/to/site/vendor/eyewitness/eye/resources/views/email/notification.blade.php)","data":null}
[2018-03-15 17:00:16] production.ERROR: Eyewitness: Unable to send Email noitification {"exception":"Trying to get property of non-object (View: /path/to/site/vendor/eyewitness/eye/resources/views/email/notification.blade.php)","data":null}
[2018-03-15 17:00:16] production.ERROR: Eyewitness: Unable to send Email noitification {"exception":"Trying to get property of non-object (View: /path/to/site/vendor/eyewitness/eye/resources/views/email/notification.blade.php)","data":null}
[2018-03-15 17:00:16] production.ERROR: Trying to get property of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property of non-object at /path/to/site/vendor/eyewitness/eye/app/Notifications/Messages/Scheduler/Working.php:39)```

**Comment by laurencei** [comment]
Hi everyone - this has been fixed in a patch that was pushed today.

If you update to the latest version it should be solved (we were trying to display a time that might not be in the database, and is not actually needed anyway).

Please let me know if you run into any further issues.
